"""
Auto-generated MCP registries for XSOAR.
Generated from OpenAPI specification: xsoar.json
Filtered by whitelist configuration

DO NOT EDIT THIS FILE MANUALLY - generated by codegen/generator.py
"""

from __future__ import annotations

from typing import Any, Awaitable, Callable, Dict, List
import os
import json
import httpx
from mcp import types

TOOL_HANDLERS: Dict[str, Callable[[Dict[str, Any]], Awaitable[List[types.TextContent]]]] = {}
TOOL_SCHEMAS: Dict[str, Dict[str, Any]] = {}
TOOL_DESCRIPTIONS: Dict[str, str] = {}

COMMON_INPUT_SCHEMA = {'type': 'object', 'properties': {'path': {'type': 'object', 'additionalProperties': True}, 'query': {'type': 'object', 'additionalProperties': True}, 'headers': {'type': 'object', 'additionalProperties': True}, 'body': {'oneOf': [{'type': 'object'}, {'type': 'array'}, {'type': 'string'}, {'type': 'number'}, {'type': 'boolean'}, {'type': 'null'}]}}, 'additionalProperties': False}

def _get_base_url() -> str:
    return os.getenv("XSOAR_API_URL", "https://your-xsoar-instance.com")

def _get_http_client() -> httpx.AsyncClient:
    verify = os.getenv("VERIFY_SSL", "true").lower() == "true"
    timeout = float(os.getenv("API_TIMEOUT", "30"))
    return httpx.AsyncClient(timeout=timeout, verify=verify)

def _build_url(base_url: str, route: str, path_params: Dict[str, Any] | None) -> str:
    url = base_url + route
    if path_params:
        for k, v in path_params.items():
            url = url.replace("{" + k + "}", str(v))
    return url

def _sanitize_headers(headers: Dict[str, Any] | None) -> Dict[str, str]:
    result: Dict[str, str] = {}
    if headers:
        for k, v in headers.items():
            if v is None:
                continue
            result[str(k)] = str(v)
    # Add XSOAR auth header if not provided
    api_key = os.getenv("XSOAR_API_KEY")
    if api_key and "Authorization" not in result:
        result["Authorization"] = api_key
    return result

def _sanitize_query(query: Dict[str, Any] | None) -> Dict[str, Any]:
    return {} if query is None else dict(query)

def _make_handler(method: str, route: str) -> Callable[[Dict[str, Any]], Awaitable[List[types.TextContent]]]:
    async def handler(arguments: Dict[str, Any]) -> List[types.TextContent]:
        path = arguments.get("path")
        query = arguments.get("query")
        headers = arguments.get("headers")
        body = arguments.get("body")
        base_url = _get_base_url()
        url = _build_url(base_url, route, path)
        try:
            async with _get_http_client() as client:
                resp = await client.request(method=method, url=url, params=_sanitize_query(query), headers=_sanitize_headers(headers), json=body)
                text = resp.text
                try:
                    data = resp.json()
                    text = json.dumps(data)
                except Exception:
                    pass
            return [types.TextContent(type='text', text=text)]
        except Exception as e:
            return [types.TextContent(type='text', text=f'ERROR: {e}')]
    return handler

TOOL_HANDLERS["xsoar_revoke_user_api_key"] = _make_handler("POST", "/apikeys/revoke/user/{username}")
TOOL_SCHEMAS["xsoar_revoke_user_api_key"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_revoke_user_api_key"] = "Revoke API Key for user"

TOOL_HANDLERS["xsoar_copy_script"] = _make_handler("POST", "/automation/copy")
TOOL_SCHEMAS["xsoar_copy_script"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_copy_script"] = "Copy given automation"

TOOL_HANDLERS["xsoar_import_classifier"] = _make_handler("POST", "/classifier/import")
TOOL_SCHEMAS["xsoar_import_classifier"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_import_classifier"] = "Import an incident classifier to Cortex XSOAR"

TOOL_HANDLERS["xsoar_upload_content_packs"] = _make_handler("POST", "/contentpacks/installed/upload")
TOOL_SCHEMAS["xsoar_upload_content_packs"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_upload_content_packs"] = "Upload content packs to Cortex XSOAR"

TOOL_HANDLERS["xsoar_import_dashboard"] = _make_handler("POST", "/dashboards/import")
TOOL_SCHEMAS["xsoar_import_dashboard"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_import_dashboard"] = "Import a dashboard to Cortex XSOAR"

TOOL_HANDLERS["xsoar_investigation_add_entry"] = _make_handler("POST", "/entry")
TOOL_SCHEMAS["xsoar_investigation_add_entry"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_investigation_add_entry"] = "Add an entry to an investigation"

TOOL_HANDLERS["xsoar_save_evidence"] = _make_handler("POST", "/evidence")
TOOL_SCHEMAS["xsoar_save_evidence"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_save_evidence"] = "Save evidence to an investigation"

TOOL_HANDLERS["xsoar_create_incidents_batch"] = _make_handler("POST", "/incident/batch")
TOOL_SCHEMAS["xsoar_create_incidents_batch"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_create_incidents_batch"] = "Update a batch of incidents"

TOOL_HANDLERS["xsoar_create_or_update_incident_type"] = _make_handler("POST", "/incidenttype")
TOOL_SCHEMAS["xsoar_create_or_update_incident_type"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_create_or_update_incident_type"] = "API to create new Incident Type"

TOOL_HANDLERS["xsoar_import_incident_types"] = _make_handler("POST", "/incidenttypes/import")
TOOL_SCHEMAS["xsoar_import_incident_types"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_import_incident_types"] = "Import an incident type to Cortex XSOAR"

TOOL_HANDLERS["xsoar_import_incident_fields"] = _make_handler("POST", "/incidentfields/import")
TOOL_SCHEMAS["xsoar_import_incident_fields"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_import_incident_fields"] = "Import an incident field to Cortex XSOAR"

TOOL_HANDLERS["xsoar_indicators_create"] = _make_handler("POST", "/indicator/create")
TOOL_SCHEMAS["xsoar_indicators_create"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_indicators_create"] = "Create indicators"

TOOL_HANDLERS["xsoar_indicators_search"] = _make_handler("POST", "/indicators/search")
TOOL_SCHEMAS["xsoar_indicators_search"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_indicators_search"] = "Search indicators"

TOOL_HANDLERS["xsoar_indicators_edit"] = _make_handler("POST", "/indicator/edit")
TOOL_SCHEMAS["xsoar_indicators_edit"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_indicators_edit"] = "Edit indicators"

TOOL_HANDLERS["xsoar_delete_indicators_batch"] = _make_handler("POST", "/indicators/batchDelete")
TOOL_SCHEMAS["xsoar_delete_indicators_batch"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_delete_indicators_batch"] = "Batch whitelist or delete indicators"

TOOL_HANDLERS["xsoar_indicator_whitelist"] = _make_handler("POST", "/indicator/whitelist")
TOOL_SCHEMAS["xsoar_indicator_whitelist"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_indicator_whitelist"] = "Whitelists or deletes an indicator"

TOOL_HANDLERS["xsoar_override_playbook_yaml"] = _make_handler("POST", "/playbook/save/yaml")
TOOL_SCHEMAS["xsoar_override_playbook_yaml"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_override_playbook_yaml"] = "Import and override playbook in Cortex XSOAR"

TOOL_HANDLERS["xsoar_get_all_widgets"] = _make_handler("GET", "/widgets")
TOOL_SCHEMAS["xsoar_get_all_widgets"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_get_all_widgets"] = "Get all widgets"

TOOL_HANDLERS["xsoar_save_widget"] = _make_handler("POST", "/widgets")
TOOL_SCHEMAS["xsoar_save_widget"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_save_widget"] = "Save a widget"

TOOL_HANDLERS["xsoar_get_widget"] = _make_handler("GET", "/widgets/{id}")
TOOL_SCHEMAS["xsoar_get_widget"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_get_widget"] = "Get a widget by ID"

TOOL_HANDLERS["xsoar_integration_upload"] = _make_handler("POST", "/settings/integration-conf/upload")
TOOL_SCHEMAS["xsoar_integration_upload"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_integration_upload"] = "Upload an integration to Cortex XSOAR"

TOOL_HANDLERS["xsoar_health_handler"] = _make_handler("GET", "/health")
TOOL_SCHEMAS["xsoar_health_handler"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_health_handler"] = "Health check endpoint"

TOOL_HANDLERS["xsoar_close_incidents_batch"] = _make_handler("POST", "/incident/batchClose")
TOOL_SCHEMAS["xsoar_close_incidents_batch"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_close_incidents_batch"] = "Closes an incidents batch"

TOOL_HANDLERS["xsoar_delete_incidents_batch"] = _make_handler("POST", "/incident/batchDelete")
TOOL_SCHEMAS["xsoar_delete_incidents_batch"] = COMMON_INPUT_SCHEMA
TOOL_DESCRIPTIONS["xsoar_delete_incidents_batch"] = "Deletes an incidents batch"

