"""
Auto-generated MCP tools for XSIAM.
Generated from OpenAPI specification: xsiam.yaml

DO NOT EDIT THIS FILE MANUALLY - it is auto-generated by codegen/generator.py
"""

from typing import List

import httpx
from mcp.server import Server
from mcp import types

# This will be set by the server initialization
server: Server = None  # type: ignore


def set_server(s: Server) -> None:
    """Set the server instance for tool registration."""
    global server
    server = s


@server.call_tool()
async def list_incidents(
    limit: int | None = None,
    status: str | None = None,
) -> List[types.TextContent]:
    """
    Retrieve a list of security incidents from XSIAM

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if limit is not None:
        params["limit"] = limit
    if status is not None:
        params["status"] = status

    # Build URL
    url = "https://api.xsiam.example.com/v1/incidents"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="GET",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for list_incidents
list_incidents_schema = {
    "type": "object",
    "properties": {
        "limit": {"type": "int", "description": "Maximum number of incidents to return"},
        "status": {"type": "str", "description": "Filter by incident status"},
    },
}


@server.call_tool()
async def create_incident(
    name: str,
    severity: str,
    description: str | None = None,
) -> List[types.TextContent]:
    """
    Create a new security incident in XSIAM

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if name is not None:
        body["name"] = name
    if severity is not None:
        body["severity"] = severity
    if description is not None:
        body["description"] = description

    # Build URL
    url = "https://api.xsiam.example.com/v1/incidents"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="POST",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for create_incident
create_incident_schema = {
    "type": "object",
    "properties": {
        "name": {"type": "str", "description": "Incident name"},
        "severity": {"type": "str", "description": ""},
        "description": {"type": "str", "description": ""},
    },
}


@server.call_tool()
async def get_incident(
    incident_id: str,
) -> List[types.TextContent]:
    """
    Retrieve details of a specific incident

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if incident_id is not None:
        path_params["incident_id"] = incident_id

    # Build URL
    url = "https://api.xsiam.example.com/v1/incidents/{incident_id}"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="GET",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for get_incident
get_incident_schema = {
    "type": "object",
    "properties": {
        "incident_id": {"type": "str", "description": "The incident ID"},
    },
}


@server.call_tool()
async def update_incident(
    incident_id: str,
    status: str | None = None,
    notes: str | None = None,
) -> List[types.TextContent]:
    """
    Update incident status or details

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if incident_id is not None:
        path_params["incident_id"] = incident_id
    if status is not None:
        body["status"] = status
    if notes is not None:
        body["notes"] = notes

    # Build URL
    url = "https://api.xsiam.example.com/v1/incidents/{incident_id}"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="PATCH",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for update_incident
update_incident_schema = {
    "type": "object",
    "properties": {
        "incident_id": {"type": "str", "description": "The incident ID"},
        "status": {"type": "str", "description": ""},
        "notes": {"type": "str", "description": ""},
    },
}


@server.call_tool()
async def list_alerts(
    severity: str | None = None,
    time_range: int | None = None,
) -> List[types.TextContent]:
    """
    Retrieve security alerts from XSIAM

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if severity is not None:
        params["severity"] = severity
    if time_range is not None:
        params["time_range"] = time_range

    # Build URL
    url = "https://api.xsiam.example.com/v1/alerts"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="GET",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for list_alerts
list_alerts_schema = {
    "type": "object",
    "properties": {
        "severity": {"type": "str", "description": "Filter by alert severity"},
        "time_range": {"type": "int", "description": "Time range in hours"},
    },
}
