"""
Auto-generated MCP tools for XSOAR.
Generated from OpenAPI specification: xsoar.yaml

DO NOT EDIT THIS FILE MANUALLY - it is auto-generated by codegen/generator.py
"""

from typing import Any, Dict, List

import httpx
from mcp.server import Server
from mcp import types

# This will be set by the server initialization
server: Server = None  # type: ignore


def set_server(s: Server) -> None:
    """Set the server instance for tool registration."""
    global server
    server = s


@server.call_tool()
async def list_playbooks(
    category: str | None = None,
) -> List[types.TextContent]:
    """
    Retrieve a list of available playbooks

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if category is not None:
        params["category"] = category

    # Build URL
    url = "https://api.xsoar.example.com/v1/playbooks"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="GET",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for list_playbooks
list_playbooks_schema = {
    "type": "object",
    "properties": {
        "category": {"type": "str", "description": "Filter by playbook category"},
    },
}


@server.call_tool()
async def execute_playbook(
    playbook_id: str,
    inputs: Dict[str, Any] | None = None,
) -> List[types.TextContent]:
    """
    Execute a specific playbook with parameters

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if playbook_id is not None:
        path_params["playbook_id"] = playbook_id
    if inputs is not None:
        body["inputs"] = inputs

    # Build URL
    url = "https://api.xsoar.example.com/v1/playbooks/{playbook_id}/execute"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="POST",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for execute_playbook
execute_playbook_schema = {
    "type": "object",
    "properties": {
        "playbook_id": {"type": "str", "description": "The playbook ID"},
        "inputs": {"type": "Dict[str, Any]", "description": "Playbook input parameters"},
    },
}


@server.call_tool()
async def list_investigations(
    status: str | None = None,
    limit: int | None = None,
) -> List[types.TextContent]:
    """
    Retrieve a list of investigations

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if status is not None:
        params["status"] = status
    if limit is not None:
        params["limit"] = limit

    # Build URL
    url = "https://api.xsoar.example.com/v1/investigations"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="GET",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for list_investigations
list_investigations_schema = {
    "type": "object",
    "properties": {
        "status": {"type": "str", "description": "Filter by investigation status"},
        "limit": {"type": "int", "description": "Maximum number of results"},
    },
}


@server.call_tool()
async def create_investigation(
    name: str,
    type: str,
    severity: int | None = None,
) -> List[types.TextContent]:
    """
    Create a new investigation

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if name is not None:
        body["name"] = name
    if type is not None:
        body["type"] = type
    if severity is not None:
        body["severity"] = severity

    # Build URL
    url = "https://api.xsoar.example.com/v1/investigations"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="POST",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for create_investigation
create_investigation_schema = {
    "type": "object",
    "properties": {
        "name": {"type": "str", "description": ""},
        "type": {"type": "str", "description": ""},
        "severity": {"type": "int", "description": ""},
    },
}


@server.call_tool()
async def search_indicators(
    query: str | None = None,
    type: str | None = None,
) -> List[types.TextContent]:
    """
    Search for indicators of compromise (IOCs)

    Args:
        Tool arguments are defined in the schema below

    Returns:
        List of text content with the API response
    """
    # Build request parameters
    params = {}
    body = {}
    path_params = {}

    if query is not None:
        params["query"] = query
    if type is not None:
        params["type"] = type

    # Build URL
    url = "https://api.xsoar.example.com/v1/indicators"
    for key, value in path_params.items():
        url = url.replace("{" + key + "}", str(value))

    # Make the API request
    async with httpx.AsyncClient() as client:
        response = await client.request(
            method="GET",
            url=url,
            params=params,
            json=body if body else None,
        )
        response.raise_for_status()
        result = response.json()

    return [
        types.TextContent(
            type="text",
            text=f"{result}",
        )
    ]


# Schema for search_indicators
search_indicators_schema = {
    "type": "object",
    "properties": {
        "query": {"type": "str", "description": "Search query"},
        "type": {"type": "str", "description": "Indicator type"},
    },
}
